CC = gcc
OBJ = client

all:			
		$(CC) client_main.c client_socket.c client_select.c client_build_fdsets.c client_send_to_server.c client_recv_from_server.c Client_decision.c client_delete_server.c LIST_Client.c CONNECT_to_Client.c process_recv_data.c find_the_client_index_by_name.c find_the_client_index_list.c -o client

exec:		
		./client
